version: '3.8'

services:
  voteboard_database:
    image: postgres:16
    environment:
      POSTGRES_DB: voteboard_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data-volume:/var/lib/voteboard_database
    ports:
      - ${POSTGRES_PORT-5432}:5432

volumes:
  data-volume:
    name: voteboard_database_data_volume
